### ISSUE TITLE
I'm stuck at Arduino flash

### ISSUE THREAD

**Issue by zeltragh** [fehlfarbe/arduino-motorfocus#13]
Hello,

I try to flash my arduino nano with the arduino-motofocus project but error comes.

![image](https://user-images.githubusercontent.com/98833778/152006071-0ab3223b-f2b6-45b5-82eb-7ee3d249ec7c.png)

i don't know i did bad... 

Can you help me ?

**Comment by zeltragh** [comment]
![image](https://user-images.githubusercontent.com/98833778/152031491-d115e4cc-90a2-452f-b8db-8157c168504d.png)

**Comment by fehlfarbe** [comment]
Hi!

Open a terminal in VSCode and type

`pio platform install atmelavr`

This should install the needed platform. If this doesn't work, please add a screenshot or log output here :)

**Comment by zeltragh** [comment]
Thank you for help.
Finally it was pio platform issue. After reinstall of this , problem solved.
