### ISSUE TITLE
Platformio.ini - missing ";"

### ISSUE THREAD

**Issue by foxboroman1** [fehlfarbe/arduino-motorfocus#18]
Platformio.ini line 1 is missing a comment (";").  I cloned the project and it wouldn't compile until the comment was added.

Old:
PlatformIO Project Configuration File

new:
;PlatformIO Project Configuration File

Thank-you for creating this project.  Everything else compiled with a few warnings. 
I suggest adding a "monitor_speed = 9600" in the platformio.ini as well.

**Comment by fehlfarbe** [comment]
Thanks! I added your changes :)

**Comment by foxboroman1** [comment]
Outstanding.  I appreciate the ownership you take in your project and 
your programing style is elegant.  Thank-you aging for this awesome project.

Best!

-Mike Wong-

Alpine, Texas
