### ISSUE TITLE
Buttons not worked for me, here is my solution.

### ISSUE THREAD

**Issue by franky384** [fehlfarbe/arduino-motorfocus#2]
First of all, thank you for sharing your code,
but the push buttons never worked for me. So after some days of searching and trial and error i finally found a working solution.
Maybe you can have a look at it ?

![untitled sketch_steckplatine](https://user-images.githubusercontent.com/4951571/50523624-81955180-0ad1-11e9-89d8-18102b6af99e.jpg)

[sketch_dec28a.html.pdf](https://github.com/fehlfarbe/arduino-motorfocus/files/2715402/sketch_dec28a.html.pdf)

**Comment by franky384** [comment]
I have tried it like in that example, but it hadn't worked for me. I can try it again with my changed code.

**Comment by fehlfarbe** [comment]
Should be fixed now. I activated the pullup resistors for button input and checked for BUTTON == LOW. So the wiring in your first post is correct.
