### ISSUE TITLE
AccelStepper.h: No such file or directory

### ISSUE THREAD

**Issue by AndiPhotonen** [fehlfarbe/arduino-motorfocus#3]
Hi,
First of all I'd like to thank you for realizing this nice project.
I downloaded the Project as a zip and extracted it to my Arduino folder.
But when I try to compile it, I get the error that it can't find the AccelStepper.h
Did I miss something or do you have a tip for me?
Thanks!

**Comment by fehlfarbe** [comment]
Hey Andi,
the Accellstepper library is missing. You can install the library with Arduino Studios library manager: https://www.arduino.cc/en/Guide/Libraries just search for accelstepper, install the current version and recompile.

**Comment by AndiPhotonen** [comment]
Thank you! now it works fine
