### ISSUE TITLE
may be a bug...

### ISSUE THREAD

**Issue by sergio49** [fehlfarbe/arduino-motorfocus#6]
Hi, I think you have a mistake in your hexStrToLong converter preventing speed change to work.

at line 329 I think it should be  : 
line.toCharArray(buf, line.length()+1);    (+1 missing)

if you change this you have to delete *16 on current and target positions. Then speed change and positionning works fine in ekos.
I've just tested it.
Thanks for your work I use it on my 80ED too :)

**Comment by fehlfarbe** [comment]
Thanks for bugfixing and testing :)
I merged your changes to master

**Comment by energiebrand** [comment]
Hi all
thanks for BugFixing!
Used the focuser only manually with a modified sketch (added a switch for fast movement) so far.
Now I´m running the focuser with ASTROBERRY: KStars / EKOS / INDI with the latest modifications and can confirm that it is working!
